# Generated by Django 2.2.10 on 2022-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=400, verbose_name='plataforma')),
                ('usuario', models.CharField(max_length=300, verbose_name='usuario')),
                ('contrasena', models.CharField(max_length=200, verbose_name='contrasena')),
                ('fecha_creacion', models.DateTimeField(null=True, verbose_name='Fecha de cheque')),
            ],
        ),
    ]
